[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/tendermint/tendermint"
  version = "~0.18.0"

[[constraint]]
  name = "github.com/tendermint/go-wire"
  source = "github.com/tendermint/go-amino"
  version = "~0.7.3"